name: Daily WWW clrmamepro profiles

on:
    push:
    schedule:
        - cron:  '0 12 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Set workflow variables
          id: step_one
          run: |
            echo "timestamp=$(date +%s)" >> $GITHUB_ENV

        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install pipenv
          run: sudo pip install pipenv

        - name: Install dependencies using Pipenv
          run: pipenv install --deploy

        - name: Download dats and generate profile.xml for Redump
          id: generator_redump
          run: pipenv run python3 redump.py

        - name: Download dats and generate profile.xml for No-Intro
          id: generator_no_intro
          run: pipenv run python3 no-intro.py

#        - name: Download dats and generate profile.xml for HTGD
#          id: generator_smdb
#          run: pipenv run python3 smdb.py

#        - name: Download dats and generate profile.xml for dats.site
#          id: generator_dats_site
#          run: pipenv run python3 dats-site.py

        - name: Create release
          uses: ncipollo/release-action@v1
          with:
            name: Nightly
            tag: Nightly
            artifacts: "*.xml,*.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
            body: Released by github actions
            commit: master
