name: SMDB daily rebuild

on:
    push:
    schedule:
        - cron:  '0 12 * * *'

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
        - name: Set workflow variables
          id: step_one
          run: |
            echo "timestamp=$(date +%s)" >> $GITHUB_ENV

        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: Install pipenv
          run: sudo pip install pipenv

        - name: Install dependencies using Pipenv
          run: pipenv install --deploy

        - name: Download dats and generate profile.xml for HTGD
          if: success() || failure()
          id: generator_smdb
          run: pipenv run python3 smdb.py

        - name: Create release
          if: success() || failure()
          uses: ncipollo/release-action@v1
          with:
            name: Nightly
            tag: Nightly
            artifacts: "*.xml,*.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
            body: Released by github actions
            commit: master
